### ISSUE TITLE
Not compatible with Magento versions lower than 2.4.5 since 1.3.0

### ISSUE THREAD

**Issue by ldrooij** [NVision-Commerce-Solutions/module-customer-price#28]
Since version 1.3.0 the class `Magento\Catalog\Model\ResourceModel\GetProductTypeById` is used in `Commerce365\CustomerPrice\Service\GetProductPriceData`. This class has been added in Magento version 2.4.5 and breaks the module on lower versions.

**Comment by soloma88** [comment]
It's already fixed
