### ISSUE TITLE
Hard dependency on Magento MSI modules

### ISSUE THREAD

**Issue by hostep** [NVision-Commerce-Solutions/module-customer-price#3]
Hi guys

We have the habit of not installing the Magento MSI modules, by adding the following to the `composer.json` from the Magento shop:

```
    "replace": {
        "magento/inventory-metapackage": "*"
    }
```

We do this because we've been having pretty bad experiences with the MSI modules of Magento in the past (unstable stocks, after some days, products that should be in stock aren't and vice-versa), and because the default stock management system is good enough and very stable.

However, this module has a dependency on one of the MSI modules [over here](https://github.com/NVision-Commerce-Solutions/module-customer-price/blob/edae8a8be7f6325b1b2be76e65c344fe81381c76/etc/webapi_rest/di.xml#L12-L14).

Which leads to `setup:di:compile` to fail when the MSI modules aren't installed:

```
$ bin/magento setup:di:compile
Compilation was started.
Interceptors generation... 4/9 [============>---------------]  44% 12 secs 96.0 MiB
In PluginListGenerator.php line 324:

  Plugin class Magento\InventoryConfigurableProductFrontendUi\Plugin\ConfigurableProduct\Block\Product\View\Type\AddAdditionalInfo doesn't exist
```

Would it be possible to remove this dependency somehow?

Or does this module really depend on the MSI modules and would you recommend we keep them installed?

Thanks!

**Comment by soloma88** [comment]
@hostep dependency removed in new version

**Comment by hostep** [comment]
Thank you!
