### ISSUE TITLE
Possible logic mistake in AdditionalDataPlugin

### ISSUE THREAD

**Issue by hostep** [NVision-Commerce-Solutions/module-customer-price#32]
Reported by phpstan on version 1.5.0 of module-customer-price:

```
------ --------------------------------------------------------------------------------
  Line   module-customer-price/Plugin/Webapi/AdditionalDataPlugin.php
 ------ --------------------------------------------------------------------------------
  27     Variable $additionalData on left side of ?? always exists and is not nullable.
 ------ --------------------------------------------------------------------------------
```

If we take a look at the [execute method](https://github.com/NVision-Commerce-Solutions/module-customer-price/blob/1.5.0/Service/Additional/PricePerUom/GetPricePerUom.php#L32-L50), it's currently guaranteed to return an array and never `null`.
So [the condition here](https://github.com/NVision-Commerce-Solutions/module-customer-price/blob/1.5.0/Plugin/Webapi/AdditionalDataPlugin.php#L27), will never return `$result`.
Is that the expectation?

**Comment by hostep** [comment]
This probably got fixed in https://github.com/NVision-Commerce-Solutions/module-customer-price/pull/38, but no new version (1.7.2) [got tagged in git yet](https://github.com/NVision-Commerce-Solutions/module-customer-price/tags) ....

**Comment by hostep** [comment]
And 1.7.2 was just released, confirmed that phpstan no longer complains on this. Thanks guys!

**Comment by soloma88** [comment]
now it's tagged. you're just too fast :) Thanks
