### ISSUE TITLE
Hiding prices doesn't work everywhere

### ISSUE THREAD

**Issue by hostep** [NVision-Commerce-Solutions/module-customer-price#8]
When I enable the config setting "Hide Prices for Guest Users", I'm only seeing them hidden on product listing pages, but when going to the product detail pages, I still see the prices.

Haven't tested this on a vanilla Magento installation though. Tested this with Hyvä frontend theme, so maybe that can be related?

**Comment by soloma88** [comment]
This is related for sure. Module doesn't support Hyva theme. I don't know what's wrong there but the way it works on vanilla Magento is the plugin for isSalable method that makes it always false if this config is enabled. If isSalable is false Magento will not show prices.

**Comment by hostep** [comment]
Okay thanks for the feedback, let's close this issue, we'll look into it a bit ourselves to see what we can do to fix it and if possible send a PR your way if it makes sense.
